### ISSUE TITLE
bluetooth only receive,  can't send any file

### ISSUE THREAD

**Issue by thanhthuy89** [ngoquang2708/android_device_samsung_vivalto3gvn#89]

**Comment by ngoquang2708** [comment]
Logcat:
```
11-21 18:16:40.748   203   308 W audio_hw_primary: [out_set_parameters], kvpairs=routing=2 devices:0x2 mode:0 
11-21 18:16:40.748   203   308 W audio_hw_primary: [out_set_parameters],after str_parms_get_str,val(0x2) 
11-21 18:16:40.748   203   308 W audio_hw_primary: the same devices(0x2) with val(0x2) val is zero...
11-21 18:16:40.748   203   308 W audio_hw_primary: out_set_parameters out...call_start:0
11-21 18:16:40.751   203   308 D audio_hw_primary: start output stream out->is_voip is 0, in
11-21 18:16:40.751   203   308 I audio_hw_primary: select_devices_signal starting...
11-21 18:16:40.751   203   308 I audio_hw_primary: select_devices_signal finished.
11-21 18:16:40.751   203   308 W audio_hw_primary: open s_tinycard in
11-21 18:16:40.752   203   308 W audio_hw_primary: open s_tinycard successfully
11-21 18:16:40.753   203   304 I audio_hw_primary: Not to change mute: 0
11-21 18:16:40.753   203   304 I audio_hw_primary: Changing out_devices: from (0xfffffffd) to (0x00000002)
11-21 18:16:40.753   203   304 I audio_hw_primary: Changing in_devices: from (0x00000000) to (0x00000000)
11-21 18:16:40.754   203   304 I audio_hw_primary: Set 'SPKL Mixer DACLSPKL Switch'.0 to 1
11-21 18:16:40.754   203   304 I audio_hw_primary: Set 'SPKL Mixer DACRSPKL Switch'.0 to 1
11-21 18:16:40.754   203   304 I audio_hw_primary: Set 'Speaker Function'.0 to 1
11-21 18:16:40.754   203   304 I audio_hw_primary: Set 'Mic Function'.0 to 0
11-21 18:16:40.754   203   304 I audio_hw_primary: Set 'ADCL Mixer MainMICADCL Switch'.0 to 0
11-21 18:16:40.755   203   304 I audio_hw_primary: Set 'ADCR Mixer MainMICADCR Switch'.0 to 0
11-21 18:16:40.755   203   304 I audio_hw_primary: Set 'Aux Mic Function'.0 to 0
11-21 18:16:40.755   203   304 I audio_hw_primary: Set 'ADCL Mixer AuxMICADCL Switch'.0 to 0
11-21 18:16:40.755   203   304 I audio_hw_primary: Set 'ADCR Mixer AuxMICADCR Switch'.0 to 0
11-21 18:16:40.755   203   304 I audio_hw_primary: Set 'HP Mic Function'.0 to 0
11-21 18:16:40.755   203   304 I audio_hw_primary: Set 'ADCL Mixer HPMICADCL Switch'.0 to 0
11-21 18:16:40.755   203   304 I audio_hw_primary: Set 'ADCR Mixer HPMICADCR Switch'.0 to 0
11-21 18:16:40.755   203   304 I audio_hw_primary: Set 'SPKL Mixer ADCLSPKL Switch'.0 to 0
11-21 18:16:40.755   203   304 I audio_hw_primary: Set 'SPKL Mixer ADCRSPKL Switch'.0 to 0
11-21 18:16:40.755   203   304 I audio_hw_primary: Set 'HPL Mixer ADCRHPL Switch'.0 to 0
11-21 18:16:40.755   203   304 I audio_hw_primary: Set 'HPR Mixer ADCLHPR Switch'.0 to 0
11-21 18:16:40.755   203   304 I audio_hw_primary: Set 'Line Function'.0 to 0
11-21 18:16:40.755   203   304 I audio_hw_primary: Set 'ADCL Mixer AILADCL Switch'.0 to 0
11-21 18:16:40.755   203   304 I audio_hw_primary: Set 'ADCR Mixer AIRADCR Switch'.0 to 0
11-21 18:16:40.755   203   304 I audio_hw_primary: Set 'HeadPhone Function'.0 to 0
11-21 18:16:40.755   203   304 I audio_hw_primary: Set 'HPL Mixer DACLHPL Switch'.0 to 0
11-21 18:16:40.755   203   304 I audio_hw_primary: Set 'HPR Mixer DACRHPR Switch'.0 to 0
11-21 18:16:40.755   203   304 I audio_hw_primary: Set 'Earpiece Function'.0 to 0
11-21 18:16:40.755   203   304 I vb_effect: s_cur_out_devices(0x00000002), s_cur_in_devices(0x00000000)
11-21 18:16:40.755   203   304 I vb_effect: profile is Handsfree, ret=0
11-21 18:16:40.755   203   304 W audio_hw_primary: GetAudio_gain_by_devices, outmode:3 inmode:3,indev:0x0, outdev:0x2
11-21 18:16:40.755   203   304 W audio_hw_primary: vb_control_parameters.c GetAudio_outpga_nv, dac_pga_gain_l:0x801807c7 adc_pga_gain_l:0x0 fm_pga_gain_l:0x227 fm_pga_gain_r:0x227 pa_config:0x330, 0x330(fm),  vol_level:0x1 
11-21 18:16:40.755   203   304 W audio_hw_primary: GetAudio_inpga_nv, adc_pga_gain_l:0x8f23 device:0x0 vol_level:0x1
11-21 18:16:40.755   203   304 D audio_pga: 'speaker-l' apply
11-21 18:16:40.755   203   304 I audio_pga: 'SPKL Playback Volume' set to 7
11-21 18:16:40.756   203   304 I audio_pga: 'DACL Playback Volume' set to 7
11-21 18:16:40.756   203   304 I audio_pga: 'VBC DACL DG Set' set to 24
11-21 18:16:40.756   203   304 I audio_pga: 'VBC DACL DG Switch' set to 1
11-21 18:16:40.756   203   304 D audio_pga: 'speaker-r' apply
11-21 18:16:40.756   203   304 I audio_pga: 'SPKR Playback Volume' set to 7
11-21 18:16:40.756   203   304 I audio_pga: 'DACR Playback Volume' set to 7
11-21 18:16:40.756   203   304 I audio_pga: 'VBC DACR DG Set' set to 24
11-21 18:16:40.756   203   304 I audio_pga: 'VBC DACR DG Switch' set to 1
11-21 18:16:40.756   203   304 W audio_hw_primary: SetAudio_gain_by_devices out, out_devices:0x2, in_devices:0x0
11-21 18:16:40.756   203   304 I audio_hw_primary: stream_routing_thread looping done.
11-21 18:16:40.756   203   304 I audio_hw_primary: stream_routing_thread looping now...
11-21 18:16:40.840   950   950 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:877 android.content.ContextWrapper.sendBroadcast:421 com.android.settings.bluetooth.DevicePickerFragment.sendDevicePickedIntent:152 com.android.settings.bluetooth.DevicePickerFragment.onDevicePreferenceClick:119 com.android.settings.bluetooth.DeviceListPreferenceFragment.onPreferenceTreeClick:148 
11-21 18:16:40.864  2587  2587 D BluetoothOppReceiver: Enter - onReceive for intent:android.bluetooth.devicepicker.action.DEVICE_SELECTED
11-21 18:16:40.898   950   950 D LocalBluetoothManager: setting foreground activity to null
11-21 18:16:41.068   950   965 D OpenGLRenderer: endAllActiveAnimators on 0x9b372200 (RippleDrawable) with handle 0x9b2fb860
11-21 18:16:41.359  2587  2587 D BluetoothOppReceiver: Exit - onReceive for intent:android.bluetooth.devicepicker.action.DEVICE_SELECTED
11-21 18:16:41.386  2587  2587 D BtOppService: Enter - onStartCommand for service OPP
11-21 18:16:41.391  2587  2587 D BtOppService: Exit - onStartCommand for service OPP
11-21 18:16:41.544   492   502 I art     : Background partial concurrent mark sweep GC freed 46569(2MB) AllocSpace objects, 11(392KB) LOS objects, 29% free, 9MB/13MB, paused 6.393ms total 572.009ms
11-21 18:16:42.400   492  1167 I WindowManager: Destroying surface Surface(name=com.android.settings/com.android.settings.bluetooth.DevicePickerActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2033 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:884 com.android.server.wm.WindowState.removeLocked:1471 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2494 com.android.server.wm.WindowManagerService.removeWindowLocked:2452 com.android.server.wm.WindowManagerService.removeWindowLocked:2321 com.android.server.wm.WindowManagerService.removeWindow:2316 com.android.server.wm.Session.remove:193 
11-21 18:16:42.433  2485  2517 W art     : Long monitor contention with owner AsyncTask #3 (2685) at boolean com.cyanogenmod.filemanager.console.shell.ShellConsole.syncExecute(com.cyanogenmod.filemanager.commands.shell.Program, boolean, boolean)(ShellConsole.java:653) waiters=0 in void com.cyanogenmod.filemanager.console.shell.ShellConsole.onNewData() for 439ms
11-21 18:16:42.480  2587  2587 D BtOppService: Enter - onStartCommand for service OPP
11-21 18:16:42.480  2587  2587 D BtOppService: Exit - onStartCommand for service OPP
11-21 18:16:42.500  2587  2686 D BtOppService: insertShare parsed URI: content://com.cyanogenmod.filemanager.providers.file/external_files/APKs/439ef3929808236a5fcfd2c8ac6f3f9cebb70c22.diff@4e02037
11-21 18:16:42.501  2587  2686 D BluetoothOppUtility: getSendFileInfo: uri=content://com.cyanogenmod.filemanager.providers.file/external_files/APKs/439ef3929808236a5fcfd2c8ac6f3f9cebb70c22.diff@4e02037
11-21 18:16:42.579  2587  2686 D OolConnManager: setSdpInitiatedAddress A4:DB:30:D6:71:42
11-21 18:16:42.583  2587  2686 D BtOppTransfer: isDisabledNonAosp :false
11-21 18:16:42.600  2587  2686 D SdpManager: Starting search for UUID: 00001105-0000-1000-8000-00805f9b34fb
11-21 18:16:42.631  2587  2686 D BluetoothSdpJni: sdpSearchNative:
11-21 18:16:42.631  2587  2686 D BluetoothSdpJni: sdpSearchNative UUID 
11-21 18:16:42.632  2587  2624 W bt_l2cap: L2CA_ErtmConnectReq()  PSM: 0x0001  BDA: a4db30d67142  p_ertm_info: 0x00000000 allowed:0x0 preferred:0
11-21 18:16:42.681  2587  2692 D A2dpService: getA2DPService(): returning com.android.bluetooth.a2dp.A2dpService@3cc12e
11-21 18:16:42.709  2587  2692 I A2dpService: audio isMusicActive is false
11-21 18:16:42.709  2587  2692 D BtOppTransfer: sdp initiated = true
11-21 18:16:43.222  2587  2624 W bt_btm  : btm_acl_role_changed: BDA: a4-db-30-d6-71-42
11-21 18:16:43.223  2587  2624 W bt_btm  : btm_acl_role_changed: New role: 1
11-21 18:16:43.254  2587  2624 W bt_btm  : btm_acl_created hci_handle=12 link_role=1  transport=1
11-21 18:16:43.254  2587  2624 W bt_btm  : btm_acl_created hci_handle=12 link_role=1  transport=1
11-21 18:16:43.255  2587  2624 W bt_l2cap: L2CAP - st: CLOSED evt: 0
11-21 18:16:43.255  2587  2624 W bt_l2cap: L2CAP - st: ORIG_W4_SEC_COMP evt: 7
11-21 18:16:43.456  2696  2696 I mount   : type=1400 audit(0.0:78): avc: denied { getattr } for path="/efs" dev="mmcblk0p7" ino=2 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:efs_file:s0 tclass=dir permissive=1
11-21 18:16:43.456  2696  2696 I mount   : type=1400 audit(0.0:79): avc: denied { getattr } for path="/productinfo" dev="mmcblk0p5" ino=2 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:prod_file:s0 tclass=dir permissive=1
11-21 18:16:43.456  2696  2696 I mount   : type=1400 audit(0.0:80): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=1
11-21 18:16:43.456  2696  2696 I mount   : type=1400 audit(0.0:81): avc: denied { open } for path="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=1
11-21 18:16:43.526  2587  2624 W bt_btm  : btm_read_remote_version_complete: BDA: a4-db-30-d6-71-42
11-21 18:16:43.526  2587  2624 W bt_btm  : btm_read_remote_version_complete lmp_version 7 manufacturer 69 lmp_subversion 1
11-21 18:16:43.530  2587  2624 E bt_btif : bta_dm_acl_change new acl connetion:count = 1
11-21 18:16:43.530  2587  2624 W bt_btif : bta_dm_acl_change info: 0x10
11-21 18:16:43.530  2587  2624 W bt_l2cap: L2CA_SetDesireRole() new:x0, disallow_switch:0
11-21 18:16:43.530  2587  2616 D bt_btif_dm: remote version info [a4:db:30:d6:71:42]: 7, 45, 1
11-21 18:16:43.595  2587  2624 W bt_l2cap: L2CAP - st: W4_L2CAP_CON_RSP evt: 19
11-21 18:16:43.604  2587  2624 W bt_l2cap: L2CAP - st: W4_L2CAP_CON_RSP evt: 11
11-21 18:16:43.604  2587  2624 W bt_l2cap: L2CAP - st: CONFIG evt: 24
11-21 18:16:43.604  2587  2624 W bt_l2cap: L2CAP - st: CONFIG evt: 14
11-21 18:16:43.604  2587  2624 W bt_l2cap: L2CAP - st: CONFIG evt: 25
11-21 18:16:43.604  2587  2624 W bt_l2cap: L2CAP-Upper layer Config_Rsp,Local CID: 0x0040,Remote CID: 0x0040,PSM: 1,our MTU present:1,our MTU:672
11-21 18:16:43.612  2587  2624 W bt_l2cap: L2CAP - st: CONFIG evt: 15
11-21 18:16:43.612  2587  2624 W bt_l2cap: L2CAP-peer_Config_Rsp,Local CID: 0x0040,Remote CID: 0x0040,PSM: 1,peer MTU present: 0,peer MTU: 672
11-21 18:16:43.622  2587  2624 W bt_sdp  : process_service_search_attr_rsp
11-21 18:16:43.622  2587  2624 W bt_l2cap: L2CA_DisconnectReq()  CID: 0x0040
11-21 18:16:43.624  2587  2616 E BluetoothRemoteDevices: state12newState0
11-21 18:16:43.652  2587  2624 W bt_l2cap: L2CAP - st: W4_L2CAP_DISC_RSP evt: 18
11-21 18:16:43.652  2587  2616 D BluetoothSdpJni: sdp_search_callback: Status is: 1, Record count: 0
11-21 18:16:43.770  2587  2616 D SdpManager: UUID: [0, 0, 17, 5, 0, 0, 16, 0, -128, 0, 0, -128, 95, -101, 52, -5]
11-21 18:16:43.771  2587  2616 D SdpManager: UUID in parcel: 00001105-0000-1000-8000-00805f9b34fb
11-21 18:16:43.787  2587  2587 D BluetoothMapService: onReceive
11-21 18:16:43.787  2587  2587 D BluetoothMapService: onReceive: android.bluetooth.device.action.SDP_RECORD
11-21 18:16:43.787  2587  2587 D BluetoothMapService: Received ACTION_SDP_RECORD.
11-21 18:16:43.789  2587  2616 D SdpManager: startSearch(): nextInst = null mSearchInProgress = false - search busy or queue empty.
11-21 18:16:43.789  2587  2616 V OolConnManager: saveOppSdpRecordA4:DB:30:D6:71:42
11-21 18:16:43.789  2587  2616 D OolConnManager: saveOppSdpRecord channel -1
11-21 18:16:43.791   203   308 D audio_hw_primary: do_output_standby in
11-21 18:16:43.792   203   308 W audio_hw_primary: do_output_standby.mode:0 
11-21 18:16:43.792   203   308 D audio_hw_primary: do_output_standby in out
11-21 18:16:43.835  2587  2692 D OolConnManager: returning l2c channel as -1
11-21 18:16:43.835  2587  2692 D BtOppTransfer: L2cap psm not found, connecting on rfcomm
11-21 18:16:43.885  2587  2692 W BluetoothAdapter: getBluetoothService() called with no BluetoothManagerCallback
11-21 18:16:43.891  2587  2624 W bt_l2cap: L2CA_ErtmConnectReq()  PSM: 0x0001  BDA: a4db30d67142  p_ertm_info: 0x00000000 allowed:0x0 preferred:0
11-21 18:16:43.891  2587  2624 W bt_l2cap: L2CAP - st: CLOSED evt: 21
11-21 18:16:43.891  2587  2624 W bt_l2cap: L2CAP - st: CLOSED evt: 7
11-21 18:16:43.912  2587  2624 W bt_l2cap: L2CAP - st: W4_L2CAP_CON_RSP evt: 11
11-21 18:16:43.912  2587  2624 W bt_l2cap: L2CAP - st: CONFIG evt: 24
11-21 18:16:43.914  2587  2624 W bt_l2cap: L2CAP - st: CONFIG evt: 14
11-21 18:16:43.914  2587  2624 W bt_l2cap: L2CAP - st: CONFIG evt: 25
11-21 18:16:43.914  2587  2624 W bt_l2cap: L2CAP-Upper layer Config_Rsp,Local CID: 0x0041,Remote CID: 0x0040,PSM: 1,our MTU present:1,our MTU:672
11-21 18:16:43.916   492   530 I WindowManager: Destroying surface Surface(name=com.cyanogenmod.filemanager/com.cyanogenmod.filemanager.activities.NavigationActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2033 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:884 com.android.server.wm.WindowState.destroyOrSaveSurface:2095 com.android.server.wm.AppWindowToken.destroySurfaces:417 com.android.server.wm.AppWindowToken.destroySurfaces:382 com.android.server.wm.WindowStateAnimator.finishExit:568 com.android.server.wm.WindowStateAnimator.stepAnimationLocked:494 com.android.server.wm.WindowAnimator.updateWindowsLocked:324 
11-21 18:16:43.917  2587  2624 W bt_l2cap: L2CAP - st: CONFIG evt: 15
11-21 18:16:43.917  2587  2624 W bt_l2cap: L2CAP-peer_Config_Rsp,Local CID: 0x0041,Remote CID: 0x0040,PSM: 1,peer MTU present: 0,peer MTU: 672
11-21 18:16:43.923  2587  2624 W bt_sdp  : process_service_search_attr_rsp
11-21 18:16:43.923  2587  2624 W bt_l2cap: L2CA_DisconnectReq()  CID: 0x0041
11-21 18:16:43.930  2587  2624 W bt_l2cap: L2CAP - st: W4_L2CAP_DISC_RSP evt: 18
11-21 18:16:43.930  2587  2626 E bt_btif_sock_rfcomm: find_rfc_slot_by_id unable to find RFCOMM slot id: 5
11-21 18:16:43.974   492   506 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@46150b attribute=null, token = android.os.BinderProxy@5ae962f
11-21 18:16:44.015  2587  2692 E BtOppTransfer: Rfcomm socket connect exception
11-21 18:16:44.015  2587  2692 E BtOppTransfer: java.io.IOException: read failed, socket might closed or timeout, read ret: -1
11-21 18:16:44.015  2587  2692 E BtOppTransfer: 	at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:738)
11-21 18:16:44.015  2587  2692 E BtOppTransfer: 	at android.bluetooth.BluetoothSocket.readInt(BluetoothSocket.java:750)
11-21 18:16:44.015  2587  2692 E BtOppTransfer: 	at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:375)
11-21 18:16:44.015  2587  2692 E BtOppTransfer: 	at com.android.bluetooth.opp.BluetoothOppTransfer$SocketConnectThread.connectRfcommSocket(BluetoothOppTransfer.java:674)
11-21 18:16:44.015  2587  2692 E BtOppTransfer: 	at com.android.bluetooth.opp.BluetoothOppTransfer$SocketConnectThread.run(BluetoothOppTransfer.java:794)
11-21 18:16:44.129   492   530 I WindowManager: Destroying surface Surface(name=Toast) called by com.android.server.wm.WindowStateAnimator.destroySurface:2033 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:884 com.android.server.wm.WindowState.destroyOrSaveSurface:2095 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementInner:429 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop:232 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement:180 com.android.server.wm.WindowManagerService$H.handleMessage:8271 android.os.Handler.dispatchMessage:102 
11-21 18:16:43.456  2696  2696 I mount   : type=1400 audit(0.0:82): avc: denied { read } for name="/" dev="tmpfs" ino=3287 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:device:s0 tclass=dir permissive=1
11-21 18:16:43.456  2696  2696 I mount   : type=1400 audit(0.0:83): avc: denied { open } for path="/dev" dev="tmpfs" ino=3287 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:device:s0 tclass=dir permissive=1
11-21 18:16:43.456  2696  2696 I mount   : type=1400 audit(0.0:84): avc: denied { read } for name="block" dev="tmpfs" ino=3477 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:block_device:s0 tclass=dir permissive=1
11-21 18:16:43.456  2696  2696 I mount   : type=1400 audit(0.0:85): avc: denied { open } for path="/dev/block" dev="tmpfs" ino=3477 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:block_device:s0 tclass=dir permissive=1
11-21 18:16:44.326  2700  2700 I df      : type=1400 audit(0.0:86): avc: denied { getattr } for path="/productinfo" dev="mmcblk0p5" ino=2 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:prod_file:s0 tclass=dir permissive=1
11-21 18:16:44.326  2700  2700 I df      : type=1400 audit(0.0:87): avc: denied { getattr } for path="/dev/fuse" dev="tmpfs" ino=3446 scontext=u:r:untrusted_app:s0 tcontext=u:object_r:fuse_device:s0 tclass=chr_file permissive=1
11-21 18:16:44.424  2485  2496 I art     : Background sticky concurrent mark sweep GC freed 12049(1073KB) AllocSpace objects, 3(60KB) LOS objects, 12% free, 9MB/10MB, paused 757us total 111.662ms
11-21 18:16:45.043  2587  2691 D BtOppTransfer: Mark all ShareInfo in the batch as failed
11-21 18:16:45.044  2587  2691 I BtOppTransfer:  Batch Failed updating Content Provider 
11-21 18:16:45.044  2587  2691 D BluetoothOppUtility: getSendFileInfo: uri=content://com.cyanogenmod.filemanager.providers.file/external_files/APKs/439ef3929808236a5fcfd2c8ac6f3f9cebb70c22.diff@4e02037
11-21 18:16:45.048  2587  2691 D BluetoothOppUtility: closeSendFileInfo: uri=content://com.cyanogenmod.filemanager.providers.file/external_files/APKs/439ef3929808236a5fcfd2c8ac6f3f9cebb70c22.diff@4e02037
11-21 18:16:45.084  2587  2587 D BluetoothOppReceiver: Enter - onReceive for intent:android.btopp.intent.action.TRANSFER_COMPLETE
11-21 18:16:45.102  2587  2587 D BluetoothOppReceiver: Exit - onReceive for intent:android.btopp.intent.action.TRANSFER_COMPLETE
11-21 18:16:45.127  2587  2702 E BtOppTransfer: Exception:unregisterReceiver
11-21 18:16:45.127  2587  2702 W System.err: java.lang.IllegalArgumentException: Receiver not registered: com.android.bluetooth.opp.BluetoothOppTransfer$1@1e77651
11-21 18:16:45.127  2587  2702 W System.err: 	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1007)
11-21 18:16:45.128  2587  2702 W System.err: 	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1330)
11-21 18:16:45.128  2587  2702 W System.err: 	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:608)
11-21 18:16:45.128  2587  2702 W System.err: 	at com.android.bluetooth.opp.BluetoothOppTransfer.cleanUp(BluetoothOppTransfer.java:535)
11-21 18:16:45.128  2587  2702 W System.err: 	at com.android.bluetooth.opp.BluetoothOppTransfer.stop(BluetoothOppTransfer.java:415)
11-21 18:16:45.128  2587  2702 W System.err: 	at com.android.bluetooth.opp.BluetoothOppService.updateShare(BluetoothOppService.java:851)
11-21 18:16:45.128  2587  2702 W System.err: 	at com.android.bluetooth.opp.BluetoothOppService.-wrap10(BluetoothOppService.java)
11-21 18:16:45.128  2587  2702 W System.err: 	at com.android.bluetooth.opp.BluetoothOppService$UpdateThread.run(BluetoothOppService.java:606)
11-21 18:16:45.291  2587  2703 E Notification: setLatestEventInfo() is deprecated and you should feel deprecated.
11-21 18:16:45.291  2587  2703 E Notification: java.lang.Throwable
11-21 18:16:45.291  2587  2703 E Notification: 	at android.app.Notification.setLatestEventInfo(Notification.java:2079)
11-21 18:16:45.291  2587  2703 E Notification: 	at com.android.bluetooth.opp.BluetoothOppNotification.updateCompletedNotification(BluetoothOppNotification.java:452)
11-21 18:16:45.291  2587  2703 E Notification: 	at com.android.bluetooth.opp.BluetoothOppNotification.-wrap1(BluetoothOppNotification.java)
11-21 18:16:45.291  2587  2703 E Notification: 	at com.android.bluetooth.opp.BluetoothOppNotification$NotificationUpdateThread.run(BluetoothOppNotification.java:218)
11-21 18:16:47.645   492   530 I WindowManager: Destroying surface Surface(name=Toast) called by com.android.server.wm.WindowStateAnimator.destroySurface:2033 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:884 com.android.server.wm.WindowState.destroyOrSaveSurface:2095 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementInner:429 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop:232 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement:180 com.android.server.wm.WindowManagerService$H.handleMessage:8271 android.os.Handler.dispatchMessage:102
```

**Comment by Verevka** [comment]
How did you fix this?

**Comment by ngoquang2708** [comment]
It is not fixed.

**Comment by diepquynh** [comment]
Buggy Bluetooth is fixed on latest N then
